import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import RequireAuth from "@/components/require-auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <RequireAuth>
        <html className="dark bg-background" lang="en">
          <body>
            <div className="flex flex-col justify-center items-center py-8">
              <div className="w-full max-w-lg flex flex-col gap-y-12">
                {children}
              </div>
            </div>
          </body>
        </html>
      </RequireAuth>
    </ClerkProvider>
  );
}
